# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

# Install mcp-remote CLI
RUN npm install -g mcp-remote

# Set workdir
WORKDIR /app

# Default command output to help
CMD ["sh", "-c", "echo 'This container provides mcp-remote CLI. It is invoked by Smithery.' && sleep infinity"]
